# Generated by Django 5.1.15 on 2026-03-23 10:46

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("category", models.CharField(max_length=100)),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published"), ("archived", "Archived")],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("author_name", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["category", "status"], name="knowledge_a_categor_5fa317_idx"),
                    models.Index(fields=["created_at"], name="knowledge_a_created_e561f4_idx"),
                ],
            },
        ),
    ]
