# Generated by Django 5.1.15 on 2026-03-23 00:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('priority_suggestion', models.CharField(max_length=20)),
                ('sentiment', models.CharField(max_length=20)),
                ('confidence', models.FloatField()),
                ('model_used', models.CharField(max_length=100)),
                ('ticket_version', models.PositiveIntegerField(help_text='Ticket version at time of classification, for idempotency.')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classification', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
